name: Build on Push

on:
  push:
    branches-ignore:
      - master

jobs:
  push-to-registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Extract image name from branch
        id: get_image_name
        shell: bash
        run: |
          IMAGE="$(echo ${GITHUB_REF#refs/heads/} | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=name::${IMAGE}"

      - name: Extract Metadata (tags, labels) for Docker
        id: get_metadata
        uses: docker/metadata-action@v3
        with:
          images: frost19k/${{ steps.get_image_name.outputs.name }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.get_metadata.outputs.tags }}
          labels: ${{ steps.get_metadata.outputs.labels }}
