name: Build on Schedule

on:

  schedule:
    - cron: '0 2 * * 1' # Run at 02:00 UTC every MONDAY

  workflow_dispatch:
    inputs:
      build_and_push:
        description: 'Run: Build and Push Docker Image'
        type: boolean
        required: true
        default: true

jobs:

  generate-matrix:
    name: Generate matrix for build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_branches.outputs.matrix }}

    steps:
      - name: Setup jq
        uses: md-actions/setup-jq@v1

      - name: Get all branches
        id: get_branches
        shell: bash
        run: |
          BRANCHES="$(curl -H 'Accept: application/vnd.github.v3+json' ${GITHUB_API_URL}/repos/frost19k/Dockerfiles/branches)"
          BRANCHES="$(echo ${BRANCHES} | jq -r ' .[] |= select(.name != "master") | del(..|nulls) | [ .[].name ] | @csv')"
          echo "::set-output name=matrix::{\"branch\":[$BRANCHES]}"

  push-to-registry:
    name: Push Docker Image to Docker Hub
    needs: generate-matrix
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Extract image name from branch
        id: get_image_name
        shell: bash
        run: |
          IMAGE="$(echo ${GITHUB_REF#refs/heads/} | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=name::${IMAGE}"

      - name: Extract Metadata (tags, labels) for Docker
        id: get_metadata
        uses: docker/metadata-action@v3
        with:
          images: frost19k/${{ steps.get_image_name.outputs.name }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        if: ${{ github.event.inputs.build_and_push == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.get_metadata.outputs.tags }}
          labels: ${{ steps.get_metadata.outputs.labels }}
