name: Build on Push

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'Dockerfile'

jobs:
  push-to-registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Extract image name
        id: get_image_name
        shell: bash
        run: |
          REPO="$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')"
          BRANCH="$(echo ${GITHUB_REF#refs/heads/} | tr '[:upper:]' '[:lower:]')"
          echo "from_repo=${REPO}" >> $GITHUB_OUTPUT
          echo "from_branch=${BRANCH}" >> $GITHUB_OUTPUT

      - name: Extract Metadata (tags, labels) for Docker
        id: get_metadata
        uses: docker/metadata-action@v4
        with:
          images: frost19k/${{ steps.get_image_name.outputs.from_branch }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.get_metadata.outputs.tags }}
          labels: ${{ steps.get_metadata.outputs.labels }}
