name: CI to Docker Hub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1' # Run at 04:00 UTC every MONDAY

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [DNSValidator, puredns, reconFTW, Subzy, subjack]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Set image name
        id: image
        env:
          BRANCH: ${{ matrix.branch }}
        run: |
          NAME="$(echo ${BRANCH} | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=name::${NAME}"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: frost19k/${{ steps.image.outputs.name }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
